### PR TITLE
Adding support for HA 0.110.0

### PR DESCRIPTION
**Pull request by atxbyea**

### CODE REVIEW

**Comment by KameDomotics** [comment]
I modified the climate.py as you wrote, but it doesn't work.
the entity has completely disappeared

**Comment by atxbyea** [comment]
Take a look at my forked repo, it should be fixed there @kamedomotics

**Comment by KameDomotics** [comment]
> Take a look at my forked repo, it should be fixed there @KameDomotics

Do I replace the manifest.json and climate.py files with your modified files?

**Comment by dapuzz** [comment]
Good job @atxbyea Please review the pull request for a complete support ha 0.110, or integrate your repo to HACS :-)

**Comment by KameDomotics** [comment]
Hi @atxbyea , in climate.py I modified line 21 and 140, but “Detected I/O inside the event loop” continues to appear
Can you help me please? 
image

**Comment by KameDomotics** [comment]
> Take a look at my forked repo, it should be fixed there @kamedomotics

Please @atxbyea can you help me?

**Comment by Ntodinana** [comment]
Dopo l'aggiornamento
Screenshot_20240114_003616_Samsung Internet
Chi può aiutarmi?

**Pull request merged**
